apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd
resources:
- ../../base

# TODO: Clean up targets
patches:
- path: patch-umbrella-dr.yaml
  target:
    group: argoproj.io
    kind: Application
    name: umbrella-apps-sb24prod
    namespace: argo-cd
    version: v1alpha1

- path: patch-argocd-app-dr.yaml
  target:
    group: argoproj.io
    kind: Application
    name: argocd-app
    namespace: argo-cd
    version: v1alpha1

- path: patch-project-app-of-apps-dr.yaml
  target:
    group: argoproj.io
    kind: AppProject
    name: app-of-apps
    version: v1alpha1

- path: patch-helm-chart-repo-dr.yaml
  target:
    kind: Secret
    name: helm-chart-repo

- path: patch-argocd-tls-certs-cm.yaml
  target:
    group: ""
    version: v1
    kind: ConfigMap
    name: argocd-tls-certs-cm
  
