kind: Secret
apiVersion: v1
metadata:
  name: helm-chart-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  enableOCI: "true"
  name: "helm-chart-repo"
  type: helm
  insecure: "true"
  url: default-route-openshift-image-registry.apps.cluster-apps-prd.ao.sbicdirectory.com
  username: argocd-helm-puller
  password: eyJhbGciOiJSUzI1NiIsImtpZCI6IkhCMHB6bnRtdkdGTXBUMTRKUERuWld1THVQT1RFaUx5eW9yeVhhTFV3d2cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJuZXdzYjI0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFyZ29jZC1oZWxtLXB1bGxlci10b2tlbi02Y3BrYyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QtaGVsbS1wdWxsZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIyMDVjNGQ2MC1kNTEzLTQ1YTQtYTE2OS0zYzkyYWZlZDU4NGIiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bmV3c2IyNDphcmdvY2QtaGVsbS1wdWxsZXIifQ.dRw3yy_KJZ_eDcCZvfI55h_nBfwebnx3dlDmcHgifxlzIx4R_xZgyVoeC6WJytJSm4HR97djJ9dd3a4K1KH0wS-YH9LOBwNov8Wg6Itb-kLtNhIYMqyMynnoSf-WYjFmEuy-11w6rXabApU6Svz-EzT6VzidoNR6IuLN4UUhV1W6Y8Q5sZkp3RJT1AHTXQi8zD4nHQ-KT96H2r3jCgBXwHznFp7ST9YBW_7YmhLNEieNdCKbFDqFnKrA5vP6QN3gPhevsuCc6XHatD86T3eoPMm8dr5CEfGVCwE6Oxa6K8TjsugYriuZVbp7R-ItBhnclp74BRSaNUmMGJbn2fKEpHOVK8Ts_NuTQ-LX7zBstnVlEZxdi9oAeg8Wu_gnYf1arHbcM9kRY_47DcFG1xZz9gnktVl8t1QZFHdW6QosfaV0GAOYTOmx2Vldz5YF-oGtlE34y9ItX4viQ31udw23JMy6TQZXMsdHg8hZEqmCOA7O7MXAixI47F9I5wMUyHrSyNiMRqxr3um7GhoIIWSaeUVRupa3sJ314RlGhHawn65NRI4ga5bv9eH8L-DxPrEG7xjOEXcmSEYG4m30Vj0Gxbn07cDtWuV9A2_TZl9Mitl-cD4VRcs-GOaeSf-t-tH28_1Niq-ehiYSMYhFuy9sO3WfwzVV5lfN5HHAdn0L4vI
