apiVersion: v1
kind: Secret
metadata:
  name: sb24-argocd-config
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: sb24-argocd-prod
  type: git
  url: https://github.com/albertchisorot/sb24-argocd-config-prod.git
